# Pandas

In [1]:
import numpy as np
import pandas as pd

## 1. Pandas Series

Creating Serires

In [2]:
labels = ['a','b','c']
lst = [10,20,30]
arr = np.array([10,20,30])
dic = {'a':10,'b':20,'c':30}

In [3]:
pd.Series(lst)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(lst,index= labels)

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(dic)

a    10
b    20
c    30
dtype: int64

## 2. DataFrames

Creating a DataFrame

In [7]:
# A dictionary where keys are column names and values are lists of data
data_dict = {
    "Material_ID": [101, 102, 103, 104],
    "Material_Name": ["PET Plastic", "Scrap Iron", "Corrugated Cardboard", "E-Waste"],
    "Quantity_KG": [1200, 4500, 850, 320],
    "Status": ["Active", "Pending", "Active", "Active"],
    "Compliance_Passed": [True, True, False, True]
}

df = pd.DataFrame(data_dict)

In [8]:
df

   Material_ID         Material_Name  Quantity_KG   Status  Compliance_Passed
0          101           PET Plastic         1200   Active               True
1          102            Scrap Iron         4500  Pending               True
2          103  Corrugated Cardboard          850   Active              False
3          104               E-Waste          320   Active               True

In [9]:
data_list = [
    [101, 'PET Plastic', 1200, 'Active', True],
    [102, 'Scrap Iron', 4500, 'Pending', True],
    [103, 'Corrugated Cardboard', 850, 'Active', False],
    [104, 'E-Waste', 320, 'Active', True]
]

df2 = pd.DataFrame(data_list)
columns = ["Material_ID", "Material_Name", "Quantity_KG", "Status", "Compliance_Passed"]
df2 = pd.DataFrame(data_list, columns=columns)
df2

   Material_ID         Material_Name  Quantity_KG   Status  Compliance_Passed
0          101           PET Plastic         1200   Active               True
1          102            Scrap Iron         4500  Pending               True
2          103  Corrugated Cardboard          850   Active              False
3          104               E-Waste          320   Active               True

Selection and Indexig of Columns

In [10]:
df2

   Material_ID         Material_Name  Quantity_KG   Status  Compliance_Passed
0          101           PET Plastic         1200   Active               True
1          102            Scrap Iron         4500  Pending               True
2          103  Corrugated Cardboard          850   Active              False
3          104               E-Waste          320   Active               True

In [11]:
df2['Material_Name']

0             PET Plastic
1              Scrap Iron
2    Corrugated Cardboard
3                 E-Waste
Name: Material_Name, dtype: object

In [12]:
df2[['Material_Name','Quantity_KG']]

          Material_Name  Quantity_KG
0           PET Plastic         1200
1            Scrap Iron         4500
2  Corrugated Cardboard          850
3               E-Waste          320

Creating a new column

In [13]:
df2["Compliance_Score"] = [94.5, 98.2, 87.0, 96.1]

In [14]:
df2

,Material_ID,Material_Name,Quantity_KG,Status,Compliance_Passed,Compliance_Score
0,101,PET Plastic,1200,Active,True,94.5
1,102,Scrap Iron,4500,Pending,True,98.2
2,103,Corrugated Cardboard,850,Active,False,87.0
3,104,E-Waste,320,Active,True,96.1

Remove Columns

In [15]:
df2.drop('Compliance_Score',axis= 1, inplace = True)

In [16]:
df2

   Material_ID         Material_Name  Quantity_KG   Status  Compliance_Passed
0          101           PET Plastic         1200   Active               True
1          102            Scrap Iron         4500  Pending               True
2          103  Corrugated Cardboard          850   Active              False
3          104               E-Waste          320   Active               True

Selecting Rows

In [17]:
df2

   Material_ID         Material_Name  Quantity_KG   Status  Compliance_Passed
0          101           PET Plastic         1200   Active               True
1          102            Scrap Iron         4500  Pending               True
2          103  Corrugated Cardboard          850   Active              False
3          104               E-Waste          320   Active               True

In [18]:
df2.loc[0]

Material_ID                  101
Material_Name        PET Plastic
Quantity_KG                 1200
Status                    Active
Compliance_Passed           True
Name: 0, dtype: object

In [19]:
df2.loc[[0,1]]

   Material_ID Material_Name  Quantity_KG   Status  Compliance_Passed
0          101   PET Plastic         1200   Active               True
1          102    Scrap Iron         4500  Pending               True

Selecting Subsets of Rows and Columns

In [20]:
df.loc[[0,1]][["Material_ID","Material_Name"]]

   Material_ID Material_Name
0          101   PET Plastic
1          102    Scrap Iron

In [21]:
df.loc[[2,3]][["Material_Name","Quantity_KG"]]

          Material_Name  Quantity_KG
2  Corrugated Cardboard          850
3               E-Waste          320

Conditional Selection

In [22]:
df2

   Material_ID         Material_Name  Quantity_KG   Status  Compliance_Passed
0          101           PET Plastic         1200   Active               True
1          102            Scrap Iron         4500  Pending               True
2          103  Corrugated Cardboard          850   Active              False
3          104               E-Waste          320   Active               True

In [23]:
df2[df2["Quantity_KG"]> 1000]

   Material_ID Material_Name  Quantity_KG   Status  Compliance_Passed
0          101   PET Plastic         1200   Active               True
1          102    Scrap Iron         4500  Pending               True

In [24]:
df2[(df2["Quantity_KG"]> 1000) & (df2["Status"] == "Active")]

   Material_ID Material_Name  Quantity_KG  Status  Compliance_Passed
0          101   PET Plastic         1200  Active               True

## 3. Missing Data

Finding Missing Data

In [25]:

data = {
    'Material_ID': [101, 102, 103, 104],
    'Material_Name': ['PET Plastic', 'Scrap Iron', np.nan, 'E-Waste'],
    'Quantity_KG': [1200, np.nan, 850, 320],
    'Status': ['Active', 'Pending', 'Active', np.nan],
    'Compliance_Score': [np.nan, 98.2, np.nan, 96.1]
}

df = pd.DataFrame(data)
df

   Material_ID Material_Name  Quantity_KG   Status  Compliance_Score
0          101   PET Plastic       1200.0   Active               NaN
1          102    Scrap Iron          NaN  Pending              98.2
2          103           NaN        850.0   Active               NaN
3          104       E-Waste        320.0      NaN              96.1

In [26]:
df.isna()

   Material_ID  Material_Name  Quantity_KG  Status  Compliance_Score
0        False          False        False   False              True
1        False          False         True   False             False
2        False           True        False   False              True
3        False          False        False    True             False

In [27]:
df.isna().sum()

Material_ID         0
Material_Name       1
Quantity_KG         1
Status              1
Compliance_Score    2
dtype: int64

In [28]:
df.isna().any()

Material_ID         False
Material_Name        True
Quantity_KG          True
Status               True
Compliance_Score     True
dtype: bool

In [29]:
df

   Material_ID Material_Name  Quantity_KG   Status  Compliance_Score
0          101   PET Plastic       1200.0   Active               NaN
1          102    Scrap Iron          NaN  Pending              98.2
2          103           NaN        850.0   Active               NaN
3          104       E-Waste        320.0      NaN              96.1

In [30]:
df.dropna() # Removes row that conatins null values

Empty DataFrame
Columns: [Material_ID, Material_Name, Quantity_KG, Status, Compliance_Score]
Index: []

In [31]:
df.dropna(thresh=4)

   Material_ID Material_Name  Quantity_KG   Status  Compliance_Score
0          101   PET Plastic       1200.0   Active               NaN
1          102    Scrap Iron          NaN  Pending              98.2
3          104       E-Waste        320.0      NaN              96.1

Filling the Missing Data

In [32]:
df

   Material_ID Material_Name  Quantity_KG   Status  Compliance_Score
0          101   PET Plastic       1200.0   Active               NaN
1          102    Scrap Iron          NaN  Pending              98.2
2          103           NaN        850.0   Active               NaN
3          104       E-Waste        320.0      NaN              96.1

In [33]:
df.fillna(0)

   Material_ID Material_Name  Quantity_KG   Status  Compliance_Score
0          101   PET Plastic       1200.0   Active               0.0
1          102    Scrap Iron          0.0  Pending              98.2
2          103             0        850.0   Active               0.0
3          104       E-Waste        320.0        0              96.1

In [34]:
values = {"Material_Name" : "Corrugated Cardboard", "Quantity_KG": 4500 , "Status" : "Active", "Compliance_Score": 96.3}
df.fillna(value = values)

   Material_ID         Material_Name  Quantity_KG   Status  Compliance_Score
0          101           PET Plastic       1200.0   Active              96.3
1          102            Scrap Iron       4500.0  Pending              98.2
2          103  Corrugated Cardboard        850.0   Active              96.3
3          104               E-Waste        320.0   Active              96.1

In [35]:
df

   Material_ID Material_Name  Quantity_KG   Status  Compliance_Score
0          101   PET Plastic       1200.0   Active               NaN
1          102    Scrap Iron          NaN  Pending              98.2
2          103           NaN        850.0   Active               NaN
3          104       E-Waste        320.0      NaN              96.1

In [36]:
df['Quantity_KG'] = df['Quantity_KG'].fillna(df['Quantity_KG'].mean())
df['Compliance_Score'] = df['Compliance_Score'].fillna(df['Compliance_Score'].mean())
df

   Material_ID Material_Name  Quantity_KG   Status  Compliance_Score
0          101   PET Plastic       1200.0   Active             97.15
1          102    Scrap Iron        790.0  Pending             98.20
2          103           NaN        850.0   Active             97.15
3          104       E-Waste        320.0      NaN             96.10

## 4. Merging Joining Concatination

Merging 2 DataFrames

In [37]:

# DataFrame 1: Employee information
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [38]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [39]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [40]:
pd.merge(employees, salaries,on="employee_id",how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [41]:
pd.merge(employees, salaries,on="employee_id",how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [42]:
pd.merge(employees, salaries,on="employee_id",how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [43]:
pd.merge(employees, salaries,on="employee_id",how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

Concatination of 2 DataFrames

In [44]:

df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [45]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [46]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [47]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [48]:
pd.concat([df1,df2],axis= 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

Joining of 2 DataFrames

In [49]:

df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [50]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [51]:
df2

   score
2     85
3     90
4     75

In [52]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [53]:
df1.join(df2, how= 'outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [54]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

## 5. GroupBy and Aggregation

GroupBy

In [55]:

data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

df = pd.DataFrame(data)

In [56]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [57]:
# Group by category and calculate the sum of Sales
df.groupby("Category")['Sales'].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

In [58]:
# Group by store and calculate the sum of Sales
df.groupby("Store")['Sales'].sum()

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [59]:
# Group by multiple cloumns 
# Group by category and store 
df.groupby(["Category","Store"])['Sales'].sum()

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

Aggregation

In [60]:
df['Sales'].mean()

np.float64(187.5)

In [61]:
df['Sales'].median()

190.0

In [62]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [63]:
df['Sales'].min()

100

In [64]:
df['Sales'].max()

300

In [65]:
df['Sales'].std()

66.06274074155351

In [66]:
df['Sales'].count()

np.int64(8)

In [67]:
df['Sales'].agg(['sum','mean','median','max','min','count','std'])

sum       1500.000000
mean       187.500000
median     190.000000
max        300.000000
min        100.000000
count        8.000000
std         66.062741
Name: Sales, dtype: float64

In [68]:
df.describe()

            Sales   Quantity                 Date
count    8.000000   8.000000                    8
mean   187.500000  15.375000  2023-01-04 12:00:00
min    100.000000   8.000000  2023-01-01 00:00:00
25%    142.500000  11.500000  2023-01-02 18:00:00
50%    190.000000  15.000000  2023-01-04 12:00:00
75%    212.500000  18.500000  2023-01-06 06:00:00
max    300.000000  25.000000  2023-01-08 00:00:00
std     66.062741   5.553313                  NaN

## 6. Pivot Tables

Pivot Tables

In [69]:

data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

# Extracting new features from the Date column
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

print(df.head())

        Date Product Region  Sales  Units    Rep    Month Quarter
0 2023-01-01       A   East    414     33   John  January      Q1
1 2023-01-02       B   West    991     32   Mary  January      Q1
2 2023-01-03       C  North    780     47    Bob  January      Q1
3 2023-01-04       D  South    424     20  Alice  January      Q1
4 2023-01-05       A   East    230     48   John  January      Q1

In [70]:
pd.pivot_table(df, values = "Sales", index= "Region", columns = "Product",aggfunc= 'median')

Product      A      B      C      D
Region
East     414.0    NaN    NaN    NaN
North      NaN    NaN  570.0    NaN
South      NaN    NaN    NaN  424.0
West       NaN  384.0    NaN    NaN

In [71]:
pd.pivot_table(df, values = ["Sales","Units"], index= "Region", columns = "Product",aggfunc= 'median')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     414.0    NaN    NaN    NaN  48.0   NaN   NaN   NaN
North      NaN    NaN  570.0    NaN   NaN   NaN  33.0   NaN
South      NaN    NaN    NaN  424.0   NaN   NaN   NaN  20.0
West       NaN  384.0    NaN    NaN   NaN  71.0   NaN   NaN

Cross Tabs

In [72]:
pd.crosstab(df["Region"],df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

## 7. Operations

In [73]:
data = {
    'Student_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'],
    'Age': [14, 15, 14, 16, 15, 14, 15, 16, 15, 14],
    'Math_Score': [85, 92, 78, 88, 95, 70, 89, 84, 91, 76],
    'City': ['New York', 'Los Angeles', 'Chicago', 'New York', 'Chicago', 'Los Angeles', 'New York', 'Chicago', 'Los Angeles', 'New York']
}

df = pd.DataFrame(data)

In [74]:
df

   Student_ID     Name  Age  Math_Score         City
0         101    Alice   14          85     New York
1         102      Bob   15          92  Los Angeles
2         103  Charlie   14          78      Chicago
3         104    David   16          88     New York
4         105      Eva   15          95      Chicago
5         106    Frank   14          70  Los Angeles
6         107    Grace   15          89     New York
7         108    Henry   16          84      Chicago
8         109      Ivy   15          91  Los Angeles
9         110     Jack   14          76     New York

In [75]:
df.head()

   Student_ID     Name  Age  Math_Score         City
0         101    Alice   14          85     New York
1         102      Bob   15          92  Los Angeles
2         103  Charlie   14          78      Chicago
3         104    David   16          88     New York
4         105      Eva   15          95      Chicago

In [76]:
df.shape

(10, 5)

In [77]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Math_Score', 'City'], dtype='object')

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Math_Score  10 non-null     int64
 4   City        10 non-null     object
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [79]:
df.describe()

       Student_ID        Age  Math_Score
count    10.00000  10.000000   10.000000
mean    105.50000  14.800000   84.800000
std       3.02765   0.788811    7.927449
min     101.00000  14.000000   70.000000
25%     103.25000  14.000000   79.500000
50%     105.50000  15.000000   86.500000
75%     107.75000  15.000000   90.500000
max     110.00000  16.000000   95.000000

In [80]:
df["Student_ID"] + 10

0    111
1    112
2    113
3    114
4    115
5    116
6    117
7    118
8    119
9    120
Name: Student_ID, dtype: int64

In [81]:
def square(x):
    return x**2

In [82]:
df["Math_Score"].apply(square)

0    7225
1    8464
2    6084
3    7744
4    9025
5    4900
6    7921
7    7056
8    8281
9    5776
Name: Math_Score, dtype: int64